In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os
df = pd.read_csv('data.csv')
df

,name,qpu_width,mip_num_cuts,mip_subcircuits_num,mip_DataFlux,mip_Latency,mip_Fidelity,mip_min_latency,mip_QU,basic_num_cuts,...,latency_min_latency,latency_QU,width,depth,two_qubit_gate_num,one_qubit_gate_num,size,qubit_utilizztion,fidelity,latency_all
0,dj,27,3.0,4.0,40.0,0.000013,0.879399,0.000013,0.085789,3.0,...,0.000012,0.085808,103,104,102,205,307,0.041764,0.977748,0.000051
1,dj,50,2.0,3.0,24.0,0.000021,0.880275,0.000013,0.151045,2.0,...,0.000002,0.193268,103,104,102,205,307,0.041764,0.977748,0.000051
2,dj,65,1.0,2.0,8.0,0.000032,0.881147,0.000019,0.272937,1.0,...,0.000019,0.272937,103,104,102,205,307,0.041764,0.977748,0.000051
3,dj,27,4.0,5.0,40.0,0.000013,0.872110,0.000008,0.050308,4.0,...,0.000002,0.060523,109,110,108,217,325,0.039513,0.976452,0.000054
4,dj,50,2.0,3.0,24.0,0.000021,0.873850,0.000014,0.149187,2.0,...,0.000005,0.162900,109,110,108,217,325,0.039513,0.976452,0.000054
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
612,wstate,50,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,2.0,...,0.000029,0.291252,93,372,184,553,737,0.071815,0.958544,0.000061
613,wstate,65,2.0,2.0,32.0,0.000033,0.871633,0.000028,0.292390,2.0,...,0.000019,0.294322,93,372,184,553,737,0.071815,0.958544,0.000061
614,wstate,27,6.0,4.0,272.0,0.000017,0.863094,0.000015,0.107195,6.0,...,0.000014,0.106799,97,388,192,577,769,0.069015,0.956782,0.000063
615,wstate,50,2.0,2.0,32.0,0.000032,0.866555,0.000032,0.289782,2.0,...,0.000032,0.289798,97,388,192,577,769,0.069015,0.956782,0.000063
616,wstate,65,2.0,2.0,32.0,0.000039,0.866555,0.000025,0.289895,2.0,...,0.000022,0.291273,97,388,192,577,769,0.069015,0.956782,0.000063

In [6]:
df[df['mip_num_cuts']==0]

,name,qpu_width,mip_num_cuts,mip_subcircuits_num,mip_DataFlux,mip_Latency,mip_Fidelity,mip_min_latency,mip_QU,basic_num_cuts,...,latency_min_latency,latency_QU,width,depth,two_qubit_gate_num,one_qubit_gate_num,size,qubit_utilizztion,fidelity,latency_all
92,e,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,49.0,...,5.500000e-07,0.048139,13,71,90,49,139,0.341396,0.981666,0.000024
94,e,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,79.0,...,2.000000e-06,0.009167,16,89,135,61,196,0.327249,0.972743,0.000030
95,e,10,0.0,0.0,0.0,0.0,0.0,0.0,0.0,30.0,...,2.550000e-06,0.113891,16,89,135,61,196,0.327249,0.972743,0.000030
96,e,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,93.0,...,2.000000e-06,0.005620,17,95,152,65,217,0.323707,0.969398,0.000032
97,e,10,0.0,0.0,0.0,0.0,0.0,0.0,0.0,42.0,...,4.050000e-06,0.131985,17,95,152,65,217,0.323707,0.969398,0.000032
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
594,wstate,10,0.0,0.0,0.0,0.0,0.0,0.0,0.0,12.0,...,5.550000e-06,0.064923,57,228,112,337,449,0.113121,0.974553,0.000037
601,wstate,16,0.0,0.0,0.0,0.0,0.0,0.0,0.0,10.0,...,9.600000e-06,0.053015,86,344,170,511,681,0.077305,0.961636,0.000056
606,wstate,16,0.0,0.0,0.0,0.0,0.0,0.0,0.0,12.0,...,3.600000e-06,0.039968,90,360,178,535,713,0.074069,0.959868,0.000059
610,wstate,16,0.0,0.0,0.0,0.0,0.0,0.0,0.0,12.0,...,5.550000e-06,0.036108,93,372,184,553,737,0.071815,0.958544,0.000061
612,wstate,50,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,...,2.895000e-05,0.291252,93,372,184,553,737,0.071815,0.958544,0.000061

In [7]:
df.name.unique()

array(['dj', 'e', 'gan', 'ghz', 'graphstate', 'hhl', 'hor__', 'oa',
       'peexact', 'pricingcall', 'pricingput', 'realamprandom', 'routing',
       'tsp', 'vqe', 'wstate'], dtype=object)

In [7]:
valid_df = df[df['basic_Fidelity']>0.95]

In [8]:
valid_df= valid_df[valid_df['qpu_width']<10]

In [9]:
valid_df = valid_df[['name','width','qpu_width','basic_Fidelity','basic_num_cuts','basic_subcircuits_num','basic_DataFlux','two_qubit_gate_num']]
valid_df

,name,width,qpu_width,basic_Fidelity,basic_num_cuts,basic_subcircuits_num,basic_DataFlux,two_qubit_gate_num
15,dj,28,5,0.960820,6.0,7.0,52,27
19,dj,30,5,0.957519,7.0,8.0,52,29
36,dj,7,5,0.990709,1.0,2.0,8,6
60,dj,21,5,0.970404,4.0,5.0,52,20
84,dj,8,5,0.989273,1.0,2.0,8,7
170,gan,6,5,0.984987,6.0,3.0,1024,15
183,ghz,18,5,0.974899,4.0,5.0,52,17
186,ghz,25,5,0.965774,5.0,6.0,52,24
189,ghz,29,5,0.960186,6.0,7.0,52,28
256,ghz,13,5,0.982713,2.0,3.0,24,12
258,ghz,17,5,0.977028,3.0,4.0,40,16
261,ghz,22,5,0.969239,5.0,6.0,52,21
264,ghz,24,5,0.966915,5.0,6.0,52,23
267,ghz,25,5,0.965755,5.0,6.0,52,24
319,graphstate,13,5,0.981436,3.0,4.0,49,13
321,graphstate,14,5,0.979269,4.0,4.0,48,14
323,graphstate,17,5,0.974743,5.0,5.0,48,17
326,graphstate,20,5,0.971210,5.0,6.0,49,20
329,graphstate,24,5,0.965552,6.0,7.0,48,24
332,graphstate,26,5,0.962254,7.0,7.0,49,26
405,graphstate,13,5,0.982163,2.0,4.0,34,13
407,graphstate,25,5,0.962938,7.0,7.0,48,25
458,oa,12,5,0.965262,12.0,6.0,64,48
460,oa,13,5,0.959553,16.0,6.0,4112,52
469,peexact,6,5,0.981849,9.0,3.0,1024,16
528,routing,6,5,0.987118,3.0,2.0,64,15
531,vqe,14,5,0.974695,6.0,4.0,256,26
533,vqe,8,5,0.987039,2.0,2.0,32,14
534,vqe,16,5,0.968726,8.0,5.0,256,30
548,wstate,12,5,0.977615,6.0,4.0,256,22
587,wstate,14,5,0.974334,6.0,4.0,256,26
589,wstate,15,5,0.970967,8.0,5.0,256,28
605,wstate,9,5,0.983441,4.0,3.0,256,16